### PR TITLE
Ignored null values and stopped to add attribute when they are not present

### PR DESCRIPTION
**Pull request by tiagotkg**

### CODE REVIEW

**Comment by sildraug** [comment]
Hi @tiagotkg I don't quite get the need for this. Could you please explain? Does applyFilter not work on null values?

**Comment by tiagotkg** [comment]
Hi @sildraug. It's working fine, but it creates attributes when my array doesn't have it.
Here's an example:

```
public function rules()
{
    return [
        'text1'   => 'required|digits:14',
        'text2'   => 'required|string|between:5,255',
        'text3' => 'sometimes|string|between:5,255',
    ];
}

/**
 *  Filters to be applied to the input.
 *
 *  @return array
 */
public function filters()
{
    return [
        'text1'   => 'digit',
        'text2'   => 'trim|escape|strip_tags',
        'text3' => 'trim|escape|strip_tags',
    ];
}

```


If I send this:

```
$request = [
    'required1' => 'test1',
    'required2' => 'test2',
]
```

When the filter is applied in $request it will return this:

```
$request = [
    'text1' => 'test1',
    'text2' => 'test2',
    'text3' => null
]

```

And the validator will throw an validation exception because this created the required3 attribute with a null value

**Comment by chenxun0618** [comment]
@tiagotkg Can you approve one of the two pull requests regarding this issue? I'm facing the same problem.

**Comment by sildraug** [comment]
We ended up using #33, but thank you for identifying the issue.

**Pull request closed without merging**
